# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea6bd7d4041801cde6efc6e5a59b04a3c950bc5d58dd79d8ad8433598c318914f0a61cd0f531abc9302b2f3602bf2b529207400847a6db0646c7980ace53d4d8

test:
  secret_key_base: 852375735d366fe179c4dd9a81a19ab2953ae37d04478bca5df9c7d232b28182cd2bbe695d46c7fdba7843a1e69131927cb9f8f5f470254363c8e3400c25e967

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
